spring:
  application.name: thumb-backend
  mvc:
    servlet:
      path: /api
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thumb_db
    username: root
    password: 123456
  data: # Redis 配置
      redis:
        database: 1
        host: localhost
        password:
        timeout: 5000
        port: 6379
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# api doc
knife4j:
  enable: true
  setting:
    language: zh_cn

